/* The 6IT Project. Copyright 2015 Conrad Rozetti, crz@6itproject.org. Distributed under the MIT License, see 6IT.h. */

#include "../6EV.h"

#include "6EV_opcodes.h"

_6IT_PRIVATE struct mnemonic_t evaluator_mnemonics[] =
{
	{EVALUATOR_OPCODE_TERMINATOR, "STOP", LIGHT, H6VM_STACK_NONE, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_INVALID, "INVALID", LIGHT, H6VM_STACK_NONE, 0, 0, { 0, 0, 0, 0, 0 }},

	{EVALUATOR_OPCODE_CAST_FP32_INT, "CASTFI", LIGHT, H6VM_STACK_NONE, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_CAST_INT_FP32, "CASTIF", LIGHT, H6VM_STACK_NONE, 0, 0, { 0, 0, 0, 0, 0 }},

	{EVALUATOR_OPCODE_PUSH_FREG, "PUSHFREG", LIGHT, H6VM_STACK_PUSH1, 0, 1, { H6VM_REG_REL, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_PUSH_SREG, "PUSHSREG", LIGHT, H6VM_STACK_PUSH1, 0, 1, { H6VM_REG_ABS, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_PUSH_INTEGER, "PUSHINT", LIGHT, H6VM_STACK_PUSH1, 0, 1, { H6VM_INT32, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_PUSH_FLOAT, "PUSHFLT", LIGHT, H6VM_STACK_PUSH1, 0, 1, { H6VM_FP32, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_PUSH_STRING, "PUSHSTR", LIGHT, H6VM_STACK_PUSH1, 0, 1, { H6VM_STR, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_DROP, "DROP", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},

	{EVALUATOR_OPCODE_CALL, "CALL", LIGHT, H6VM_STACK_UNKNOWN, 0, 2, { H6VM_FUNC, H6VM_INT32, 0, 0, 0 }},
	{EVALUATOR_OPCODE_LUACALL, "LUACALL", LIGHT, H6VM_STACK_UNKNOWN, 0, 2, { H6VM_FUNC, H6VM_INT32, 0, 0, 0 }},
	{EVALUATOR_OPCODE_NATIVE, "NATIVE", LIGHT, H6VM_STACK_UNKNOWN, 0, 2, { H6VM_FUNC, H6VM_INT32, 0, 0, 0 }},
	{EVALUATOR_OPCODE_BUILTIN, "BUILTIN", LIGHT, H6VM_STACK_UNKNOWN, 0, 2, { H6VM_FUNC, H6VM_INT32, 0, 0, 0 }},
	{EVALUATOR_OPCODE_UNRESOLVED_EXPERNAL_CALL, "UNRESOLVED", LIGHT, H6VM_STACK_UNKNOWN, 0, 2, { H6VM_FUNC, H6VM_INT32, 0, 0, 0 }},

	{EVALUATOR_OPCODE_MINUS, "MINUS", LIGHT, H6VM_STACK_NONE, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_PLUS, "PLUS", LIGHT, H6VM_STACK_NONE, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_LNOT, "LNOT", LIGHT, H6VM_STACK_NONE, 0, 0, { 0, 0, 0, 0, 0 }},

	{EVALUATOR_OPCODE_IADD, "IADD", LIGHT, H6VM_STACK_NONE, H6VM_INT32, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_ISUB, "ISUB", LIGHT, H6VM_STACK_NONE, H6VM_INT32, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_IMUL, "IMUL", LIGHT, H6VM_STACK_NONE, H6VM_INT32, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_IDIV, "IDIV", LIGHT, H6VM_STACK_NONE, H6VM_INT32, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_IMOD, "IMOD", LIGHT, H6VM_STACK_NONE, H6VM_INT32, 0, { 0, 0, 0, 0, 0 }},

	{EVALUATOR_OPCODE_ADD, "ADD", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_SUB, "SUB", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_MUL, "MUL", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_DIV, "DIV", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_MOD, "MOD", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},

	{EVALUATOR_OPCODE_IADD_FP32, "IADDF", LIGHT, H6VM_STACK_NONE, H6VM_FP32, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_ISUB_FP32, "ISUBF", LIGHT, H6VM_STACK_NONE, H6VM_FP32, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_IMUL_FP32, "IMULF", LIGHT, H6VM_STACK_NONE, H6VM_FP32, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_IDIV_FP32, "IDIVF", LIGHT, H6VM_STACK_NONE, H6VM_FP32, 0, { 0, 0, 0, 0, 0 }},

	{EVALUATOR_OPCODE_ADD_FP32, "ADDF", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_SUB_FP32, "SUBF", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_MUL_FP32, "MULF", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_DIV_FP32, "DIVF", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},

	{EVALUATOR_OPCODE_LT, "LT", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_LE, "LE", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_GT, "GT", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_GE, "GE", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_EQ, "EQ", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_NE, "NE", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},

	{EVALUATOR_OPCODE_LT_FP32, "LTF", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_LE_FP32, "LEF", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_GT_FP32, "GTF", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_GE_FP32, "GEF", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_EQ_FP32, "EQF", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_NE_FP32, "NEF", LIGHT, H6VM_STACK_POP1, 0, 0, { 0, 0, 0, 0, 0 }},

	{EVALUATOR_OPCODE_ALLOC_FREG, "ALLOCFREG", LIGHT, H6VM_STACK_PUSH1, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_ASSIGN_FREG, "ASSIGNFREG", LIGHT, H6VM_STACK_POP1, 0, 1, { H6VM_REG_REL, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_ASSIGN_FREG_ADD, "ASSIGNADDFREG", LIGHT, H6VM_STACK_POP1, 0, 1, { H6VM_REG_REL, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_ASSIGN_FREG_SUB, "ASSIGNSUBFREG", LIGHT, H6VM_STACK_POP1, 0, 1, { H6VM_REG_REL, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_ASSIGN_FREG_MUL, "ASSIGNMULFREG", LIGHT, H6VM_STACK_POP1, 0, 1, { H6VM_REG_REL, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_ASSIGN_FREG_DIV, "ASSIGNDIVFREG", LIGHT, H6VM_STACK_POP1, 0, 1, { H6VM_REG_REL, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_ASSIGN_FREG_MOD, "ASSIGNMODFREG", LIGHT, H6VM_STACK_POP1, 0, 1, { H6VM_REG_REL, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_FREG_PREINC, "PREINCFREG", LIGHT, H6VM_STACK_POP1, 0, 1, { H6VM_REG_REL, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_FREG_PREDEC, "PREDECFREG", LIGHT, H6VM_STACK_POP1, 0, 1, { H6VM_REG_REL, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_FREG_POSTINC, "POSTINCFREG", LIGHT, H6VM_STACK_POP1, 0, 1, { H6VM_REG_REL, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_FREG_POSTDEC, "POSTDECFREG", LIGHT, H6VM_STACK_POP1, 0, 1, { H6VM_REG_REL, 0, 0, 0, 0 }},

	{EVALUATOR_OPCODE_ALLOC_SREG, "ALLOCSREG", LIGHT, H6VM_STACK_PUSH1, 0, 0, { 0, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_ASSIGN_SREG, "ASSIGNSREG", LIGHT, H6VM_STACK_POP1, 0, 1, { H6VM_REG_ABS, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_ASSIGN_SREG_ADD, "ASSIGNADDSREG", LIGHT, H6VM_STACK_POP1, 0, 1, { H6VM_REG_ABS, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_ASSIGN_SREG_SUB, "ASSIGNSUBSREG", LIGHT, H6VM_STACK_POP1, 0, 1, { H6VM_REG_ABS, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_ASSIGN_SREG_MUL, "ASSIGNMULSREG", LIGHT, H6VM_STACK_POP1, 0, 1, { H6VM_REG_ABS, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_ASSIGN_SREG_DIV, "ASSIGNDIVSREG", LIGHT, H6VM_STACK_POP1, 0, 1, { H6VM_REG_ABS, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_ASSIGN_SREG_MOD, "ASSIGNMODSREG", LIGHT, H6VM_STACK_POP1, 0, 1, { H6VM_REG_ABS, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_SREG_PREINC, "PREINCSREG", LIGHT, H6VM_STACK_POP1, 0, 1, { H6VM_REG_ABS, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_SREG_PREDEC, "PREDECSREG", LIGHT, H6VM_STACK_POP1, 0, 1, { H6VM_REG_ABS, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_SREG_POSTINC, "POSTINCSREG", LIGHT, H6VM_STACK_POP1, 0, 1, { H6VM_REG_ABS, 0, 0, 0, 0 }},
	{EVALUATOR_OPCODE_SREG_POSTDEC, "POSTDECSREG", LIGHT, H6VM_STACK_POP1, 0, 1, { H6VM_REG_ABS, 0, 0, 0, 0 }},

	{0, 0, LIGHT, 0, 0, 0, { 0, 0, 0, 0, 0 }}
};

_6IT_PRIVATE struct mnemonic_t const *_6EV_get_mnemonic(opcode_t opcode)
{
	int i = 0;

	while (evaluator_mnemonics[i].mnemonic)
	{
		if (evaluator_mnemonics[i].opcode == opcode)
		{
			return &evaluator_mnemonics[i];
		}

		++i;
	}

	return 0;
}


